name: Artifacts
on:
  workflow_dispatch:
jobs:
  upload-job:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v6
        with:
          name: uploaded
          path: date.txt
          retention-days: 5
  download-job:
    runs-on: ubuntu-latest
    needs: [upload-job]
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
